### ISSUE TITLE
Missing schema fields in Management API

### ISSUE THREAD

**Issue by cuongtranx** [storyblok/storyblok-docs#18]
Hi, even though you already have 

https://www.storyblok.com/docs/api/management#core-resources/components/possible-field-types

 and 

https://www.storyblok.com/docs/api/management#core-resources/components/the-component-field-object.

to which I can use to map what fields are available for which component. This list is pretty hard to use, also it is not showing all options available in Storyblok's UI, such as `link_scope` and `force_link_scope` option for the `multilink` component.

If there's an option for viewing a complete list of which fields going with which components, that would be tremendously helpful when working with SB.

**Comment by DominikAngerer** [comment]
Information for all schema options: https://www.storyblok.com/docs/schema-configuration

**Comment by sebgie** [comment]
Closing as this issue seems to be resolved 👍.
