### ISSUE TITLE
Retrieve version attached to release

### ISSUE THREAD

**Issue by edbo** [storyblok/storyblok-docs#21]
I'd like to be able to retrieve the versions of stories that are in various "releases" however I can't spot in the API documentation how this is possible.

Use case is something like this:

1) User creates a release
2) Edits a page in that release
3) Clicks schedule in the editor saving a version of the page for the release
4) Web hook triggers and the web hook contains information about which release was published (currently web hook triggers but there is no information about which release it was)
5) Grab that version from the API to build it

Other APIs to retrieve releases and pages within them would also be useful.

**Comment by DominikAngerer** [comment]
Hey there! The Parameter would be "from_release". Here is our FAQ to it: https://www.storyblok.com/faq/how-to-access-an-edited-version-of-a-story-from-a-release

I'll also add an example section in the docs
