### ISSUE TITLE
Cache Invalidation on SSR

### ISSUE THREAD

**Issue by JeronimasDargis** [storyblok/storyblok-docs#74]
https://www.storyblok.com/docs/api/content-delivery#topics/cache-invalidation

```
Recommended: SSG / Server Side
Generate a timestamp (once on a server, not on every request/client load)
Append your timestamp to all your subsequent calls of the endpoint /v1/cdn/stories

```

Question: When does the server side timestamp has to be updated ? otherwise it will always be older than the storyblok timestamp

**Comment by DominikAngerer** [comment]
Hey there!

We would recommend using our Webhook to trigger a function on your side that would update the version information. https://www.storyblok.com/docs/Guides/using-storyblok-webhooks With that you can define a Webhook URL inside Storyblok that we would call. If the event action is equal to "published" you can swap out the version timestamp with a new one or the one of the space/me call itself; both are valid options.

Cheers,
Dominik
